//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRunner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceRunner.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректные аргументы. Использование утилиты:.
        /// </summary>
        internal static string Program_IncorrectArgumentsNeedUsageMessage {
            get {
                return ResourceManager.GetString("Program_IncorrectArgumentsNeedUsageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось перезапустить сервис.
        /// </summary>
        internal static string ServiceRunner_FailedToRestartService {
            get {
                return ResourceManager.GetString("ServiceRunner_FailedToRestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис завершился нештатно.
        /// </summary>
        internal static string ServiceRunner_ServiceCrashed {
            get {
                return ResourceManager.GetString("ServiceRunner_ServiceCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис штатно завершил работу.
        /// </summary>
        internal static string ServiceRunner_ServiceNormalyTerminated {
            get {
                return ResourceManager.GetString("ServiceRunner_ServiceNormalyTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис успешно перезапущен.
        /// </summary>
        internal static string ServiceRunner_ServiceSuccessfullyRestarted {
            get {
                return ResourceManager.GetString("ServiceRunner_ServiceSuccessfullyRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытка перезапустить сервис № {0} из {1})... .
        /// </summary>
        internal static string ServiceRunner_TryingRestartMessageMask {
            get {
                return ResourceManager.GetString("ServiceRunner_TryingRestartMessageMask", resourceCulture);
            }
        }
    }
}
